# dummy config.yml
web_server:
  bind: 0.0.0.0
  port: 3539
api: yes
webui: yes

tasks:
  taskname:
    rss: http://example.com/torrents.xml
    series:
      - some series 1
      - some series 2
    download: /Media
